# Default config: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 200
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Metrics/ClassLength:
  Enabled: false # some projects have big test classes
Metrics/MethodLength:
  Max: 50
Metrics/ModuleLength:
  Max: 200
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
Style/ClassAndModuleChildren:
  Enabled: false # projects use both compact and nested style, preferring compact
Style/ClassVars:
  Enabled: false # it's ok when knowing it's limitations, easy to access from class instance scope
Style/CollectionMethods:
  Enabled: true
Style/Documentation:
  Enabled: false # depends on project
Style/StringLiterals:
  Enabled: false # quoting style depends on project
