""" Vim
"""
""" Reference: https://vimhelp.org/options.txt.html

" Enable all features
set nocompatible

" <Leader> character is mapped to comma instead of backslash for easier access
let mapleader = ","

" (Auto)indent uses 2 characters; spaces instead of tabs
set shiftwidth=2
set softtabstop=-1
set expandtab

" ...but not for the following file types
autocmd FileType make set noexpandtab

" Guess indentation
set smarttab
set autoindent

" Powerful backspaces
set backspace=indent,eol,start

" Show partial commands
set showcmd

" Highlight matches for search term
set hlsearch

" Jump to the matches while typing
set incsearch

" Ignore case while searching
set ignorecase

" Show the line and column number of the cursor position
set ruler

" When a bracket is inserted, briefly jump to the matching one
set showmatch

" Auto-detect the filetype
filetype plugin indent on

" Syntax highlight
syntax on

set history=1000
set undolevels=1000

" Start scrolling before the last visible line
set scrolloff=3

" Let <Tab> completion behave like bash
set wildchar=<Tab>
set wildmode=list:longest

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif
