# frozen_string_literal: true

# Install: `brew bundle install --global`
#
# See:
#
# * https://docs.brew.sh/Brew-Bundle-and-Brewfile
#
# * `man brew`

brew "awscli"
brew "azure-cli"
brew "bash"
brew "bash-completion@2"
brew "chruby"
brew "coreutils"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "global"
brew "gnupg"
brew "jq"
brew "nmap"
brew "node"
brew "openssl@3"
brew "pinentry-mac" if OS.mac?
brew "readline"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "shfmt"
brew "tmux"
brew "yt-dlp"
brew "zoxide"

brew "tkareine/chnode/chnode", trusted: true

if OS.mac?
  tap "d12frosted/emacs-plus", trusted: true
  brew "d12frosted/emacs-plus/emacs-plus@30"
end

cask "alfred"
cask "betterdisplay"
cask "firefox"
cask "gitup-app"
cask "imageoptim"
cask "iterm2"
cask "jdk-mission-control"
cask "keepassxc"
cask "rectangle"
cask "temurin@25"
cask "thunderbird"

cask "docker/tap/sbx", trusted: true
