name: CI

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Run linter
        run: make lint-docker
      - name: Run tests
        run: make test-docker
